### ISSUE TITLE
Automate processes

### ISSUE THREAD

**Issue by Vylpes** [GravityOS/gos-live#3]
The processes of this should be automated, maybe with Jenkins.

## Subtasks
- [ ] Install Jenkins
- [ ] Create Auto build process
- [ ] Create Auto deploy process
- [ ] Create Auto ISO build process
